### ISSUE TITLE
Duo2 touch dead after switching screens

### ISSUE THREAD

**Issue by Clanceeinfinity** [Archfx/duo-de#50] opened 2024-08-27 16:11 UTC
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: duo2
- GSI version: gapps 07.25.2024
- Vendor version:

### Expected Behavior

you close the device so that both screens are on the outside, then rotate the device to switch your screen, now you should be able to use the device.

### Current Behavior

Instead of switching normally, sometimes both screens turn black and additionally every time you try that, touch stops working and you gotta reboot by holding power for a few seconds.

### Steps to Reproduce

1. turn device on
2. fold it outwards
3. rotate to switch to the other screen

**Comment by Ethanol10** [comment] 2024-08-27 16:42
Aye, I get this issue sometimes too

**Comment by fisch92** [comment] 2024-09-01 09:49
Problem exists also with Version v2024.08.18. It happens not always, but very often.

**Comment by JayBee-git** [comment] 2024-09-01 16:09
I can confirm I got that issue too, just after a clean install.

**Comment by fisch92** [comment] 2024-09-01 16:12
I also get the problem with stock os and lawchair launcher instead of the stock launcher. The stock launcher is a modified microsoft launcher, right? Is it possible to install it on the custom android 14?

**Comment by Ethanol10** [comment] 2024-09-11 02:49
Might be related, but when attempting to switch screens by double tapping, this issue occurs. But also you can repeatedly switch screen by rotating the device and double tapping on each screen. Maybe something to do with how PostureProcessor handles the double tapping?

**Comment by Ethanol10** [comment] 2024-09-11 04:59
@Clanceeinfinity by chance do you have a pen? turns out when the display locks up, you can use the pen to "reset" the touch and it restores the touch input after using the pen.

**Comment by Clanceeinfinity** [comment] 2024-09-11 07:01
ohh i sadly don't have the pen, i will buy it tho!

**Comment by Archfx** [comment] 2024-09-11 14:43
How frequently does this issue occur? Potential places that can happen are either [posture_processor](https://github.com/Archfx/duoPosture) or the system. 

Let's start with the posture processor. For that I need a log file when the issue is replicated in the background.
Use the following command to initiate the log process and recreate the issue.

```shell
adb -d logcat | grep POSTURE > log.txt
```
do a "ctrl + X" to exit the log process. Include the log file here as a text file.  


I assume It is getting into an undefined state. Let's see!!

**Comment by Clanceeinfinity** [comment] 2024-09-11 15:02
i never logged before so I'll try it later, as for how often this happens, it's every time you swap screens

**Comment by Ethanol10** [comment] 2024-09-11 15:27
[posturelog.txt](https://github.com/user-attachments/files/16965706/posturelog.txt)

Had to run a slightly different command but it should grab the specified logs requested.

**Comment by Ethanol10** [comment] 2024-09-11 15:27
Here is a video of this issue:

https://github.com/user-attachments/assets/cd1da08b-427e-4a9b-9ef4-c1edc8bea134

**Comment by Ethanol10** [comment] 2024-09-11 15:31
There was also a case I sometimes run into where the screen that should be active is deactivated, and the one behind turns on. Flipping to the other side to use it in this case then sets the other screen active, and vice versa. This is fixed by closing the device and opening it again, resetting it back to usual function. The touch input in this case also disappears until the pen is used, in which normal touch input can be used.

**Comment by Archfx** [comment] 2024-09-11 15:49
I see, this is very informative. The issue should be in the touchHAL then. Since the touch pen is working. The original FSM for the posture processor was from Thain. Which I modified later. It either overrides the previous touch object or attaches to a null object or something when the posture is changed. Log does not contain an error since it does not create an error rather a problem in the logic of the FSM.

**Comment by Clanceeinfinity** [comment] 2024-09-11 15:50
Unrelated but i saw a different (now closed) issue here and this is present for you too, when folded you get 2 navigation bars and the home screen shuffles together with the notification panel being waaaay to big. Id recommend going to developer options and changing your minimum width to from 537 to 600!

**Comment by Archfx** [comment] 2024-09-11 15:55
> Unrelated but i saw a different (now closed) issue here and this is present for you too, when folded you get 2 navigation bars and the home screen shuffles together with the notification panel being waaaay to big. Id recommend going to developer options and changing your minimum width to from 537 to 600!

| See, I thought that it was an issue with the trebuchet launcher. Now seeing this I think the culprit is [this patch](https://github.com/Archfx/duo-de/blob/main-14/patches/personal/platform_packages_apps_Trebuchet/0003-Duo-de-all-apps-top-padding-config.patch) that I added to resize the allapps window.

Added later: this patch is just adjusting the height of the all app. I think this is still an issue in the trebuchet launcher which is created by a condition that checks the device screen width.

**Comment by Archfx** [comment] 2024-09-11 16:06
> I see, this is very informative. The issue should be in the touchHAL then. Since the touch pen is working. The original FSM for the posture processor was from Thain. Which I modified later. It either overrides the previous touch object or attaches to a null object or something when the posture is changed. Log does not contain an error since it does not create an error rather a problem in the logic of the FSM.

If anyone is interested in taking a look at the state transition logic, it is here https://github.com/Archfx/duoPosture/blame/main/src/main/kotlin/com/thain/duo/PostureProcessorService.kt#L467

**Comment by Archfx** [comment] 2024-09-13 15:33
During the posture change, the device change the system mode between tablet mode and phone mode (I made this to make it more usable in two modes, getting rid of this would have solved this). Upon a lot of inspection (after the observation from @Clanceeinfinity) I realized that there are certain places where the default Android implementation is not properly switching (some elements are still in tablet mode while others are transitioned to phone mode). I think this is affecting this behavior as well as several other reported cosmetic issues. I am trying to fix this (you may have seen multiple alpha releases). I will give an update on this soon.

**Comment by Archfx** [comment] 2024-09-18 21:13
After a lot of experiments, I was able to implement a proper way to switch between Tablet mode and Phone mode inside the UI. This fixed a lot of cosmetic issues that were there in the previous releases.

Can you guys try to reproduce this error on the [latest](https://github.com/Archfx/duo-de/releases/tag/v2024.09.18) release?

**Comment by Ethanol10** [comment] 2024-09-19 01:24
Will report here when I get the chance!

**Comment by Ethanol10** [comment] 2024-09-19 01:33
It seems as if the screens still lose touch input on screen switch. Pen still restores input.

**Comment by Archfx** [comment] 2024-09-19 02:43
> It seems as if the screens still lose touch input on screen switch. Pen still restores input.

Okay, in this case, it is the posture processor,  duo1 and duo2 use two versions of touchHAL, 

```kotlin
import vendor.surface.touchpen.V1_0.ITouchPen #duo1
import vendor.surface.touchpen.V1_2.ITouchPen #duo2
```

Then it looks like duo2 touchHAL is having this issue.

**Comment by Archfx** [comment] 2024-09-20 00:50
I am building a test version with the downgraded touchHAL for duo2 devices, lets see what happens.

**Comment by Archfx** [comment] 2024-09-20 03:26
Please try the latest version and let me know how it goes. I would like to see a log file on this if it does not fix the issue. This is using `touchpen.V1_1`.

**Comment by Ethanol10** [comment] 2024-09-20 04:21
On boot, it seems as if the touch does not work at all. Using the pen restores the input.

After trying to change the active side while folded to only show one screen, It seems to shut off both screens with the nav bar active on both screens.

Seems to be worse overall regarding the touchpen downgrade.

I've attached an unfiltered log:
[log.txt](https://github.com/user-attachments/files/17069764/log.txt)

**Comment by Archfx** [comment] 2024-10-02 13:44
> [posturelog.txt](https://github.com/user-attachments/files/16965706/posturelog.txt)
> 
> Had to run a slightly different command but it should grab the specified logs requested.

Looking at your log file again I found similar scenario we observed in Issue #61.

```shell
09-12 01:05:57.275  3381  3381 D POSTURE PROCESSOR: Got posture FlipLRight : R270
09-12 01:05:57.276  3381  3381 D POSTURE PROCESSOR: Loaded X: 1344 Y: 1892 HINGE: 66 OFFSET: 705
09-12 01:05:57.276  3381  3381 D POSTURE PROCESSOR: Processing posture FlipPRight : R0
09-12 01:05:57.286  3381  3381 D POSTURE PROCESSOR: Setting display composition 1 new!
09-12 01:06:02.075  3381  3381 D POSTURE PROCESSOR: Got posture FlipLLeft : R270
09-12 01:06:02.077  3381  3381 D POSTURE PROCESSOR: Loaded X: 1344 Y: 1892 HINGE: 66 OFFSET: 705
09-12 01:06:02.077  3381  3381 D POSTURE PROCESSOR: Processing posture FlipPRight : R0
09-12 01:06:02.087  3381  3381 D POSTURE PROCESSOR: Setting display composition 1 new!
09-12 01:06:28.176  3381  3381 D POSTURE PROCESSOR: Got posture FlipLRight : R270
09-12 01:06:28.179  3381  3381 D POSTURE PROCESSOR: Loaded X: 1344 Y: 1892 HINGE: 66 OFFSET: 705
09-12 01:06:28.179  3381  3381 D POSTURE PROCESSOR: Processing posture FlipPRight : R0
09-12 01:06:28.189  3381  3381 D POSTURE PROCESSOR: Setting display composition 1 new!
09-12 01:06:32.175  3381  3381 D POSTURE PROCESSOR: Got posture FlipLLeft : R90
09-12 01:06:32.176  3381  3381 D POSTURE PROCESSOR: Loaded X: 1344 Y: 1892 HINGE: 66 OFFSET: 705
09-12 01:06:32.176  3381  3381 D POSTURE PROCESSOR: Processing posture FlipPRight : R0
```

Could you please check the status of this issue on the new release.

**Comment by Ethanol10** [comment] 2024-10-02 13:56
Touch issues still persist during this release, it can be reset the same way with the pen.

**Comment by Clanceeinfinity** [comment] 2024-10-03 08:08
Yes the touch issue is still present for me

**Comment by Ethanol10** [comment] 2024-10-20 14:58
Ive only noticed this recently, but occasionally the touch will lockup in A15 when switching between postures and it will become impossible to interface with the device unless you hard reset. In this case the pen AND the touchscreen both fail to work.

**Comment by Archfx** [comment] 2024-10-20 16:10
> Ive only noticed this recently, but occasionally the touch will lockup in A15 when switching between postures and it will become impossible to interface with the device unless you hard reset. In this case the pen AND the touchscreen both fail to work.

Interesting can you try to replicate this with a log? I actually wanted to optimize the posture processor so badly. There were several redundant cases that sent the same command to the system, while the system was already in that mode. You might remember we had to fix issue #61 which was caused by a similar condition.

I think that the origin of this issue is also due to a similar thing.

**Comment by Ethanol10** [comment] 2024-10-20 17:17
Will update you with a log when I can.

**Comment by Ethanol10** [comment] 2024-10-21 00:38
[log.txt](https://github.com/user-attachments/files/17452617/log.txt)

This is what I got, Looking at the log it doesn't seem to gleam obvious errors, however the replication method is the same as the issue above, that being, 

1) Fold the device into single screen mode
2) Flip the device in an attempt to switch screens
3) The device now cannot respond to finger touch input and must be rebooted

If it's possible maybe switching between screens should be disabled entirely? I find I can accidentally trigger a screen switch accidentally, which can lead into another problem i've been having, listed below:

[flipflopPostureLog.txt](https://github.com/user-attachments/files/17452658/flipflopPostureLog.txt)

In this log, I flattened the device out, then folded it and attempted to switch screens multiple times. At some point (indicated when the device is switching between FlipPLeft and FlipPRight) the device seems to mix the two postures up, aka FlipPLeft is processed when FlipPRight should've been processed instead.

**Comment by Archfx** [comment] 2024-10-23 00:02
> [log.txt](https://github.com/user-attachments/files/17452617/log.txt)
> 
> This is what I got, Looking at the log it doesn't seem to gleam obvious errors, however the replication method is the same as the issue above, that being,
> 
> 1. Fold the device into single screen mode
> 2. Flip the device in an attempt to switch screens
> 3. The device now cannot respond to finger touch input and must be rebooted
> 
> If it's possible maybe switching between screens should be disabled entirely? I find I can accidentally trigger a screen switch accidentally, which can lead into another problem i've been having, listed below:
> 
> [flipflopPostureLog.txt](https://github.com/user-attachments/files/17452658/flipflopPostureLog.txt)
> 
> In this log, I flattened the device out, then folded it and attempted to switch screens multiple times. At some point (indicated when the device is switching between FlipPLeft and FlipPRight) the device seems to mix the two postures up, aka FlipPLeft is processed when FlipPRight should've been processed instead.

Thanks, I updated the posture logic removing a bit of redundant code.  Try replicating the no-touch issue now. Still the posture translation causes the device to lock, I will fix it.

**Comment by Ethanol10** [comment] 2024-10-23 00:20
Thanks for the update @Archfx !

Unfortunately, the no-touch issue is still present.

However I just noticed something regarding the issue with it processing PLeft/PRight incorrectly. An example below:

When PLeft should be processed but PRight's screen is on, if you use a pen on the right screen while the left screen is facing up,   the screen will stay on PRight correctly once the pen is used and the posture flipping to the wrong screen corrects itself.

Another issue I'm noticing is flipping the device while folded causes the screen to black out for about 5-10 seconds *sometimes*, then it finally updates. Once again if you use the pen when blacked out it restores the responsiveness. 

Why the pen fixes most touch inputs is beyond me haha

```
10-23 11:22:28.894  3822  3822 D POSTURE PROCESSOR: Got posture FlatDualL : R90
10-23 11:22:28.896  3822  3822 D POSTURE PROCESSOR: Loaded X: 1344 Y: 1892 HINGE: 66 OFFSET: 705
10-23 11:22:28.896  3822  3822 D POSTURE PROCESSOR: Processing posture FlipLRight : R90
10-23 11:22:28.906  3822  3822 D POSTURE PROCESSOR: Setting display composition 1 new!
10-23 11:22:29.195  3822  3822 D POSTURE PROCESSOR: Setting hinge angle 175
10-23 11:22:30.197  3822  3822 D POSTURE PROCESSOR: Setting hinge angle 170
10-23 11:22:34.896  3822  3822 D POSTURE PROCESSOR: Setting hinge angle 167
```

Also the posture seems to be processing the wrong posture

**Comment by Archfx** [comment] 2024-10-23 00:25
> Thanks for the update @Archfx !
> 
> Unfortunately, the no-touch issue is still present.
> 
> However I just noticed something regarding the issue with it processing PLeft/PRight mix up, if it gets confused and you use the pen on the screen that is on, for example:
> 
> When PLeft should be processed but PRight's screen is on, if you use a pen on the right screen while the left screen is facing up, the screen will stay on PRight correctly once the pen is used and the posture flipping to the wrong screen corrects itself.

This is a great tip and it helps

> Another issue I'm noticing is flipping the device while folded causes the screen to black out for about 5-10 seconds _sometimes_, then it finally updates. Once again if you use the pen when blacked out it restores the responsiveness.

This is my mistake, I realised this after everything is built.

> Why the pen fixes most touch inputs is beyond me haha

Lol

> ```
> 10-23 11:22:28.894  3822  3822 D POSTURE PROCESSOR: Got posture FlatDualL : R90
> 10-23 11:22:28.896  3822  3822 D POSTURE PROCESSOR: Loaded X: 1344 Y: 1892 HINGE: 66 OFFSET: 705
> 10-23 11:22:28.896  3822  3822 D POSTURE PROCESSOR: Processing posture FlipLRight : R90
> 10-23 11:22:28.906  3822  3822 D POSTURE PROCESSOR: Setting display composition 1 new!
> 10-23 11:22:29.195  3822  3822 D POSTURE PROCESSOR: Setting hinge angle 175
> 10-23 11:22:30.197  3822  3822 D POSTURE PROCESSOR: Setting hinge angle 170
> 10-23 11:22:34.896  3822  3822 D POSTURE PROCESSOR: Setting hinge angle 167
> ```
> 
> Also the posture seems to be processing the wrong posture

**Comment by Archfx** [comment] 2024-10-23 00:59
I think this time I found the issue for the original problem. Building a new 15 image now!!!

**Comment by Archfx** [comment] 2024-11-08 14:25
Thanks to @Ethanol10, you can avoid this issue by setting a default screen when the device is folded. So, I will close the issue for now.

**Closed as completed by Archfx** 2024-11-08 14:25 UTC

**Comment by megabytesme** [comment] 2024-11-30 23:01
Hey, I just wanted to report that I'm having this issue still on my Duo 2 (running latest release 2024.11.29 - Upgraded from 12L to 2024.11.27 a couple days ago, and updated to 2024.11.29 today).

Following the steps above to replicate the issue still works too - alongside using any Surface pen to fix the issue.

What is interesting though is that if you replicate the issue, then unfold, sometimes only the screen which was last touched will recognise the Surface pen. Although this is somewhat intermittent.

**Comment by Archfx** [comment] 2024-12-03 00:44
Actually, we (Especially @Ethanol10 and me) did a lot of analysis on this issue and could not isolate the issue. So, we temporarily settled for the solution of locking the phone mode display to a default screen. It is not the fix; it is just a workaround for now.

To lock the display when folding back to a specific display, go to `settings -> Phh treble app -> Surface Duo` features to find that option and set it to anything other than Dynamic.
