### ISSUE TITLE
Discord and Snapchat vanished after rebooting duo2

### ISSUE THREAD

**Issue by Clanceeinfinity** [Archfx/duo-de#37] opened 2024-08-05 11:45 UTC
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: duo2 
- GSI version: gapps 07.25.2024
- Vendor version:

### Expected Behavior

A reboot should not uninstall apps

### Current Behavior

It deleted Discord and Snapchat, installing them via the playstore again didn't result in a dataloss, i didn't have to sign in, it basically continued if the were never deleted...

### Steps to Reproduce

1. reboot
2. maybe your apps are gone, maybe not. Doesn't happen every time...

**Comment by Archfx** [comment] 2024-08-05 12:46
Since during the installation, your partitions were messed up, it might not have prompted you to wipe the user data. Usually when migrating from 12/13 to 14, (especially the current version of 14 which is based on the latest Android) apps need to be reinstalled with correct API updates and settings, hence forcing to perform a user data wipe to prevent booting/critical issues. 

Therefore this is not an issue with the ROM.

When you get the future OTA updates, this situation will not happen.

**Comment by Clanceeinfinity** [comment] 2024-08-05 12:49
i did install Discord and Snapchat after switching to the gsi 😬
before i just had telegram and revanced installed

**Comment by Archfx** [comment] 2024-08-05 13:42
> i did install Discord and Snapchat after switching to the gsi 😬 before i just had telegram and revanced installed

Can you replicate the situation by rebooting again?

If it does happen again, I assume your partitions are still not correctly set.

**Comment by Clanceeinfinity** [comment] 2024-08-05 14:06
So ill keep an eye on it. it seems to have only happened once after i think i did around 10 or so reboots... I tried to reboot again and it worked fine. So maybe an obscure bug...

**Comment by Archfx** [comment] 2024-08-05 16:09
Yep, for now, I will close the issue, feel free to reopen it if it happens again. We can get a log file and see what's going on.

**Closed as completed by Archfx** 2024-08-05 16:09 UTC

**Comment by Archfx** [comment] 2024-08-16 13:42
Could you please try to reproduce the #45 issue @Clanceeinfinity? Thanks
