### ISSUE TITLE
Huge touch offset happening randomly

### ISSUE THREAD

**Issue by itsleemcguire** [Archfx/duo-de#104] opened 2024-11-27 14:39 UTC
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: 
- GSI version: 
- Vendor version:

### Expected Behavior

I'm intermittently getting a crazy offset on touch interactions on this latest update, I'm talking me tapping something on the middle of the screen and it selects something like an entire inch downwards. Happening in a few apps and when I'm using device with both screens on. It's not related to the offset that you get when disabling the hinge gap, though this offset is really annoying and stops me using the hinge gap option, that option only messes up tocu hin the area right next to the hinge gap, this is an issue that appears rlabout an inch or two away from the hinge at least and is really random, I'm trying to diagnose when I can make it happen so will update accordingly.

### Current Behavior

As above

### Steps to Reproduce

1. 
2. 
3. 
 R

**Comment by Archfx** [comment] 2024-11-30 03:54
Please check if this issue is reproducible in the latest release.

**Comment by itsleemcguire** [comment] 2024-11-30 04:02
Sure downloading now gimme a day or two and I'll see if it still happens.

**Comment by Archfx** [comment] 2024-12-03 00:46
I could not reproduce this issue on the latest build, so closing it.

**Closed as completed by Archfx** 2024-12-03 00:46 UTC
