### ISSUE TITLE
Banking app install issue from APK-mirror

### ISSUE THREAD

**Issue by fdalleva** [Archfx/duo-de#27] opened 2024-07-09 15:44 UTC
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: surface duo
- GSI version: 
- Vendor version:

### Expected Behavior

Expect the app to launch successfully 

### Current Behavior

App does not launch. Following exception is displayed: This app cannot run because the environment is not secure and your data may be at risk

### Steps to Reproduce

1. 
2. 
3.

**Comment by Archfx** [comment] 2024-07-09 16:04
Could you please be more specific? What is the application you are trying to install? 

This issue could be related to release-keys, I can fix it if this issue is reproducible on my side.

**Comment by fdalleva** [comment] 2024-07-09 16:09
Try install this app https://www.apkmirror.com/apk/firstrand-bank-limited/fnb-banking-app/fnb-banking-app-7-8-1-51-42-release/fnb-banking-app-7-8-1-51-42-android-apk-download/download/?key=fde263c1e97072d56bac53073819a0c41f675137&forcebaseapk=true

**Comment by Archfx** [comment] 2024-07-09 16:22
I was able to install the above app from the Play Store without any issues on the latest build. However, the above app crashes due to incompatibility with A14.  Other banking apps work fine. This issue is unlikely from the release keys of this ROM.


What is the build number of the in settings ->About device->Build number? I want the number after "eng.aruna.2024"

**Comment by fdalleva** [comment] 2024-07-09 16:48
Yes I noticed that it did not work with the latest version on the play store. treble_arm64_bgN-userdebug 14 AP2A.240605.024.A1 eng.aruna.20240626.115820

It worked on thais build which is also aosp 14.

**Comment by Archfx** [comment] 2024-07-09 18:00
20240626.115820 this version is based on Android 14 QPR3 `android-14.0.0_r54`  (is the second Android "trunk stable" release) which is the latest at the moment.

Thais build was based on `android-14.0.0_r15`, which is a bit older. 

 Similar issues can be expected from test-keys-based releases which are under the pre-releases.
 
 Anyway, thanks for finding this issue. If you can add the log during the exception, I will take a look into what is going under the hood.
 
 Meanwhile, I will close this issue for the moment.

**Closed as completed by Archfx** 2024-07-09 18:00 UTC

**Comment by Archfx** [comment] 2024-07-09 18:05
Check this issue is discussed in the generic treble project in https://github.com/ponces/treble_aosp/issues/104

**Comment by fdalleva** [comment] 2024-07-09 23:47
Thanks. It's strange. I've spread the news that there's a new rom. Check
here https://xdaforums.com/t/a14-gsi-for-surface-duo.4598441/page-30

**Comment by Archfx** [comment] 2024-07-10 13:46
> Thanks. It's strange. I've spread the news that there's a new rom. Check here https://xdaforums.com/t/a14-gsi-for-surface-duo.4598441/page-30


Great!! Thanks for sharing it with everybody!
